# Generated by Django 4.1.2 on 2022-10-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bishop'),
    ]

    operations = [
        migrations.CreateModel(
            name='bishopschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.DateField()),
                ('to', models.DateField()),
                ('month', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='bishopvenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(default='', max_length=5000)),
                ('datex', models.CharField(default='', max_length=5000)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bishopschedule', verbose_name='month')),
            ],
        ),
    ]
