# Generated by Django 4.1.2 on 2022-10-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bishopschedule_bishopvenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='bibleverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=5000)),
                ('versus', models.CharField(max_length=5000)),
            ],
        ),
    ]
