# Generated by Django 4.1.2 on 2022-10-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bibleverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(default='')),
                ('about_diocese', models.TextField(default='')),
            ],
        ),
    ]
