# Generated by Django 4.1.2 on 2022-10-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=10000)),
                ('phone', models.CharField(max_length=10000)),
                ('subject', models.TextField()),
            ],
        ),
    ]
