# Generated by Django 4.1.2 on 2022-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blog_post_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
