# Generated by Django 4.1.2 on 2022-10-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blog_post_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Post',
        ),
    ]
