# Generated by Django 4.1.2 on 2022-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=10000)),
                ('author_image', models.ImageField(default='', upload_to='post images')),
                ('Blog_Thumbnail', models.ImageField(default='', upload_to='post thumbnail')),
                ('Time_stamp', models.DateTimeField(blank=True)),
                ('short_description', models.TextField(default='')),
                ('content', models.TextField()),
            ],
        ),
    ]
