# Generated by Django 4.1.2 on 2022-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.CharField(default='', max_length=10000, verbose_name="title(use '-' instead of space and -blog at the end)"),
            preserve_default=False,
        ),
    ]
