# Generated by Django 4.1.2 on 2022-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_blogcomment_parent_remove_blogcomment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religious_Women',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('seo', models.CharField(default='', max_length=10000)),
                ('Congrigation', models.CharField(default='', max_length=200)),
                ('Patron', models.CharField(default='', max_length=200)),
                ('Phone_Number', models.CharField(default='', max_length=200)),
                ('Email_Id', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=20000)),
            ],
        ),
    ]
