# Generated by Django 4.1.2 on 2022-10-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_religious_women_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
