# Generated by Django 4.1.2 on 2022-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_downloads_file_downloads_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='title',
            field=models.CharField(default='', max_length=5500),
        ),
    ]
