# Generated by Django 4.1.2 on 2022-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_downloads_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='file',
            field=models.FileField(max_length=100000, upload_to='downloads'),
        ),
    ]
