# Generated by Django 4.1.2 on 2022-10-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parish',
            old_name='ministry_name',
            new_name='parish_name',
        ),
    ]
