# Generated by Django 4.1.2 on 2022-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0002_rename_ministry_name_parish_parish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='patron',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parish',
            name='place',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
