# Generated by Django 4.1.2 on 2022-10-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0003_parish_patron_parish_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
