# Generated by Django 4.1.2 on 2022-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10000)),
                ('slug', models.CharField(max_length=10000, verbose_name="title(use '-' instead of space and -blog at the end)")),
                ('author', models.CharField(max_length=10000)),
                ('Blog_Thumbnail', models.ImageField(default='', upload_to='post thumbnail')),
                ('Time_stamp', models.DateTimeField(blank=True)),
                ('short_description', models.TextField(default='')),
                ('content', models.TextField()),
            ],
        ),
    ]
