# Generated by Django 4.1.2 on 2022-10-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_blogcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='newsComment',
        ),
    ]
