# Generated by Django 4.1.2 on 2022-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=1000)),
                ('slug', models.CharField(default='', max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='ministries')),
                ('content', models.TextField()),
            ],
        ),
    ]
