# Generated by Django 4.1.2 on 2022-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
