# Generated by Django 4.1.2 on 2022-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diocesen_Priest',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='priest')),
                ('short_desc', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relgious_Priest',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='priest')),
                ('short_desc', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
