# Generated by Django 4.1.2 on 2022-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0002_remove_diocesen_priest_short_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diocesen_priest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='relgious_priest',
            name='content',
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Address',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Date_of_Birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Date_of_Feast',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Date_of_Ordination',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Email_Id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='diocesen_priest',
            name='Phone_Number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Address',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Congrigation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Date_of_Birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Date_of_Feast',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Date_of_Ordination',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Email_Id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='Phone_Number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
