# Generated by Django 4.1.2 on 2022-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy', '0003_remove_diocesen_priest_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocesen_priest',
            name='seo',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='relgious_priest',
            name='seo',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
